In [1]:
import numpy as np

In [2]:
# a = np.random.randn(100, 1)
# w = np.linspace(start=1, stop=100, num=100).reshape(-1, 1)
# w = w / sum(w)

a = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
w = np.array([[0.2],
              [0.2],
              [0.2],
              [0.2],
              [0.2]])

print('a: ', a.shape, a[:5])
print('w: ', w.shape, w[:5], sum(w))

a:  (5, 1) [[1]
 [2]
 [3]
 [4]
 [5]]
w:  (5, 1) [[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]] [1.]


# Element-wise Multiplication

In [3]:
ans = a * w
print('ans: ', ans.shape, ans[:5], sum(ans))

ans = np.multiply(a, w)
print('ans: ', ans.shape, ans[:5], sum(ans))

ans:  (5, 1) [[0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]] [3.]
ans:  (5, 1) [[0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]] [3.]


# Matrix Multiplication (dot product/scalar product of rows and columns)

In [4]:
ans = a.T @ w
print('ans: ', ans.shape, ans[:5])

ans = np.matmul(a.T, w)
print('ans: ', ans.shape, ans[:5])

ans = np.dot(a.T, w)
print('ans: ', ans.shape, ans[:5])

ans:  (1, 1) [[3.]]
ans:  (1, 1) [[3.]]
ans:  (1, 1) [[3.]]


# Kernel Functions

In [5]:
import numpy as np
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity, polynomial_kernel, rbf_kernel, sigmoid_kernel

# https://scikit-learn.org/stable/modules/metrics.html

In [6]:
# Example input vectors
# x1 = np.array([1, 2, 3])
# x2 = np.array([4, 5, 6])
x1 = a
x2 = w

# Cosine Similarity
cosine_similarity_value = cosine_similarity(x1.reshape(1, -1), x2.reshape(1, -1))
print(f"Cosine Similarity Value: {cosine_similarity_value}")

# Linear kernel
lin_kernel_value = linear_kernel(x1.reshape(1, -1), x2.reshape(1, -1))
print(f"Linear Kernel Value: {lin_kernel_value}")

# Polynomial Kernel
degree = 2
coef0 = 1
poly_kernel_value = polynomial_kernel(x1.reshape(1, -1), x2.reshape(1, -1), degree=degree, coef0=coef0)
print(f"Polynomial Kernel Value: {poly_kernel_value}")

# Radial Basis Function (RBF) Kernel (Gaussian Kernel)
gamma = 0.1
rbf_kernel_value = rbf_kernel(x1.reshape(1, -1), x2.reshape(1, -1), gamma=gamma)
print(f"RBF Kernel Value: {rbf_kernel_value}")

# Sigmoid Kernel
sigmoid_kernel_value = sigmoid_kernel(x1.reshape(1, -1), x2.reshape(1, -1))
print(f"Sigmoid Kernel Value: {sigmoid_kernel_value}")


Cosine Similarity Value: [[0.90453403]]
Linear Kernel Value: [[3.]]
Polynomial Kernel Value: [[2.56]]
RBF Kernel Value: [[0.00729913]]
Sigmoid Kernel Value: [[0.92166855]]


# Determinant and Rank

In [7]:
# Invertible Matrix (Non-Singular Matrix)
a = np.random.randint(5, size=(4, 4))
print('a:\n', a)
det = np.linalg.det(a)
print('Determinant: ', det)
matrix_rank = np.linalg.matrix_rank(a)
print('Rank: ', matrix_rank)

# Singular Matrix (Non-Invertible Matrix)
a[0] = a[1]
print('a:\n', a)
det = np.linalg.det(a)
print('Determinant: ', det)
matrix_rank = np.linalg.matrix_rank(a)
print('Rank: ', matrix_rank)

a = np.random.randint(5, size=(4, 4))
a[:,0] = a[:,1]
print('a:\n', a)
det = np.linalg.det(a)
print('Determinant: ', det)
matrix_rank = np.linalg.matrix_rank(a)
print('Rank: ', matrix_rank)

a:
 [[4 2 0 3]
 [0 4 2 2]
 [1 4 0 1]
 [1 2 4 0]]
Determinant:  119.99999999999997
Rank:  4
a:
 [[0 4 2 2]
 [0 4 2 2]
 [1 4 0 1]
 [1 2 4 0]]
Determinant:  0.0
Rank:  3
a:
 [[3 3 4 3]
 [1 1 1 2]
 [2 2 4 4]
 [0 0 4 4]]
Determinant:  0.0
Rank:  3
