In [1]:
import time

import numpy as np

In [2]:

"""
https://www.w3resource.com/python-exercises/python-basic-exercise-65.php
"""

def time_taken(start, end):
    """Human readable time between `start` and `end`

    :param start: time.time()
    :param end: time.time()
    :returns: day:hour:minute:second.millisecond
    """
    my_time = end-start
    day = my_time // (24 * 3600)
    my_time = my_time % (24 * 3600)
    hour = my_time // 3600
    my_time %= 3600
    minutes = my_time // 60
    my_time %= 60
    seconds = my_time
    milliseconds = ((end - start)-int(end - start))
    day_hour_min_sec = str('%02d' % int(day))+":"+str('%02d' % int(hour))+":"+str('%02d' % int(minutes))+":"+str('%02d' % int(seconds)+"."+str('%.3f' % milliseconds)[2:])
    
    return day_hour_min_sec

# 1 Arrays and Strings
## Interview Questions, Page: 90

In [3]:
"""
Q1.1
Is Unique: Implement an algorithm to determine if a string has all unique characters.
What if you cannot use additional data structures?
"""

def isUniqueChar(my_str):
    
    if len(my_str) > 128:
        return False
    
    char_set = [False for i in range(128)]
    for i in range(len(my_str)):
        a_char_index = ord(my_str[i]) # ** ord: https://docs.python.org/3/library/functions.html#ord
        if char_set[a_char_index]:
            return False
        char_set[a_char_index] = True

    return True

my_str = "abcdefg"
print(isUniqueChar(my_str))

my_str = "abcdefgzz"
print(isUniqueChar(my_str))

True
False


In [4]:
"""
Q1.2
Check Permutation: Given two strings, write a method to decide if one is a permutation of the other.
"""

def permutation(str1, str2):
    
    if (len(str1) == len(str2)) and (sorted(str1) == sorted(str2)):
        return True
    else:
        return False

def permutation_v2(str1, str2):
    
    if (len(str1) != len(str2)):
        return False
    
    letters = [0 for i in range(128)]
    for i in range(len(str1)):
        index = ord(str1[i]) # ** ord: https://docs.python.org/3/library/functions.html#ord
        letters[index] += 1

    for i in range(len(str2)):
        index = ord(str2[i]) # ** ord: https://docs.python.org/3/library/functions.html#ord
        letters[index] -= 1
        if letters[index] < 0:
            return False
    return True

start_time = time.time()
str1 = "abcd"
str2 = "acdb"
print(permutation(str1, str2))
str1 = "abcd"
str2 = "accb"
print(permutation(str1, str2))
print("day, hour, minute, second.millisecond->", time_taken(start_time, time.time()))

start_time = time.time()
str1 = "abcd"
str2 = "acdb"
print(permutation_v2(str1, str2))
str1 = "abcd"
str2 = "accb"
print(permutation_v2(str1, str2))
print("day, hour, minute, second.millisecond->", time_taken(start_time, time.time()))

True
False
day, hour, minute, second.millisecond-> 00:00:00:00.001
True
False
day, hour, minute, second.millisecond-> 00:00:00:00.000


In [5]:
"""
Q 1.4
Palindrome Permutation: Given a string, write a function to check if it is a permutation of a palindrome.
A palindrome is a word or phrase that is the same forwards and backwards.
A permutation is a rearrangement of letters. The palindrome does not need to be limited to just dictionary words.
EXAMPLE
Input: Tact Coa
Output: True (permutations:"taco cat'; "atco cta'; etc.)
"""

"""
We need to have an even number of almost all characters, so that half can be on one side and half can be on the other side.
At most one character (the middle character) can have an odd count.

To be a permutation of a palindrome, a string can have no more than one character that is odd.
"""

#my_str = "tact coa"
#my_str = "tactcoapapa"
my_str = "02091992"

char_count_dict = {}
for a_char in my_str.lower():
    char_count_dict.setdefault(a_char, 0)
    char_count_dict[a_char] += 1

print(char_count_dict)

odd_counter = 0
for a_char in char_count_dict:
    if a_char == ' ':
        continue
    if (char_count_dict[a_char] % 2) == 1:
        odd_counter += 1
    if odd_counter == 2:
        print("Not Palin.")
        break

if odd_counter < 2:
    print("Palin")

{'0': 2, '2': 2, '9': 3, '1': 1}
Not Palin.


In [6]:
"""
Q 1.5
One Away: There are three types of edits that can be performed on strings:
insert a character, remove a character, or replace a character.
Given two strings, write a function to check if they are one edit (or zero edits) away.
EXAMPLE
pale, ple -> true
pales, pale -> true
pale, bale -> true
pale, bake -> false
"""

def check_edit(str1, str2):
    diff = abs(len(str1) - len(str2))
    if diff > 1:
        return False
    
    idx1 = 0
    idx2 = 0
    a_toggle = False
    
    while (idx1 < len(str1) and idx2 < len(str2)):
        if str1[idx1] != str2[idx2]:
            if a_toggle:
                return False

            a_toggle = True
            if len(str1) > len(str2):
                idx1 += 1
            elif len(str1) < len(str2):
                idx2 += 1
            else:
                idx1 += 1
                idx2 += 1
            continue
            
        idx1 += 1
        idx2 += 1
    
    return True

str1_list = ["pale", "pales", "pale", "pale", "pale", "apple", "apple"]
str2_list = ["ple", "pale", "bale", "bake", "bae", "aple", "eple"]

for i in range(len(str1_list)):
    print(str1_list[i], str2_list[i], check_edit(str1_list[i], str2_list[i]))

pale ple True
pales pale True
pale bale True
pale bake False
pale bae False
apple aple True
apple eple False


In [7]:
"""
Q 1.6
String Compression: Implement a method to perform basic string compression using the counts of repeated characters.
For example, the string aabcccccaaa would become a2b1c5a3.
If the "compressed" string would not become smaller than the original string, your method should return the original string.
You can assume the string has only uppercase and lowercase letters (a - z).
"""

my_str = "aabcccccaaa"
com_str = ""

for i in range(len(my_str)):
#     print(i, my_str[i])
    if i == 0:
        com_str += my_str[i]
        count = 1
    else:
        if com_str[-1] == my_str[i]:
            count += 1
            if i == len(my_str)-1:
                com_str += str(count)
        else:
            com_str += str(count)
            com_str += my_str[i]
            count = 1

print("com_str:", com_str) # a2b1c5a3

if len(com_str) < len(my_str):
    print(com_str) # a2b1c5a3
else:
    print(my_str)

com_str: a2b1c5a3
a2b1c5a3


In [8]:
"""
Q 1.8
Zero Matrix: Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column are set to 0
"""

N, M = 5, 6
matrix = np.random.randint(low=0, high=10, size=(N, M))
print(matrix)

zero_row = []
zero_column = []
for i in range(N):
    if i in zero_row:
        continue
    for j in range(M):
        if j in zero_column:
            continue
        if matrix[i][j] == 0:
            zero_row.append(i)
            zero_column.append(j)

print(zero_row, zero_column)

for i in zero_row:
    for j in range(M):
        matrix[i][j] = 0
for j in zero_column:
    for i in range(N):
        matrix[i][j] = 0
print(matrix)

[[9 3 0 6 9 3]
 [0 2 6 5 2 1]
 [9 6 5 5 7 6]
 [1 0 5 1 1 4]
 [8 3 4 3 6 1]]
[0, 1, 3] [2, 0, 1]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 5 7 6]
 [0 0 0 0 0 0]
 [0 0 0 3 6 1]]
